---
title: "Descriptive"
output:
  html_document:
    df_print: paged
---

Descriptive summaries of CDF data and onset ot diagnosis delay.

```{r, setup}

source(here::here("code","setup_env.R"))

figdir <- "figures/descriptive"

```

```{r loaddata}

# Load analysis data
dat <- readRDS(here::here("data","analysisdata_individual.rds")) %>%
  dplyr::mutate(delay_cat5 = cut(days_fever, c(0,15,30,90,180,730), include.lowest = TRUE, ordered_result = TRUE),
                delay_cat3 = cut(days_fever, c(0,30,90,730), include.lowest = TRUE, ordered_result = TRUE),
                detection = factor(poss_acd, labels = c("PCD","ACD"))) %>%
  arrange(days_fever)

# Setup map context
blockmap <- readRDS(here::here("data","geography","bihar_block.rds"))

# centre <- c(lon = mean(match$longitude), lat = mean(match$latitude))
extent <- setNames(st_bbox(blockmap), c("left","bottom","right","top"))
bh_lines <- get_stamenmap(bbox = extent, maptype = "terrain-lines", zoom = 8)

```

## Overall summary
```{r overall}

dat %>%
  st_drop_geometry() %>%
  group_by(diag_month) %>%
  tally() %>%
  ggplot(aes(diag_month, n)) +
  geom_col() +
  labs(x = "Month of diagnosis", y = "No. reported cases")

ggsave(here::here(figdir,"total_inc.png"),
       height = 4, width = 5, units = "in")

n_distinct(dat$vil_code)

# Plot data locations 
ggmap(bh_lines, 
      base_layer = ggplot(st_jitter(dat))) +
  geom_sf(alpha = 0.5, cex = 0.8) +
  labs(x = "", y = "", subtitle = "Locations of cases diagnosed between Jan 2018 - July 2019") -> map_cases
map_cases

ggsave(here::here(figdir,"map_cases.png"),
       map_cases,
       height = 6, width = 8, units = "in")

summary(dat$days_fever)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 4.00   25.00   30.00   45.01   58.00  510.00 
summary(dat$delay_cat5)
# [0,15]   (15,30]   (30,90]  (90,180] (180,730] 
# 198      2284      1607       251        54 
summary(dat$delay_cat3)
# [0,30]  (30,90] (90,730] 
# 2482     1607      305 
summary(dat$gt90)
# FALSE    TRUE 
# 4089     305

```


## Observed delays over time

### Overall/by year
```{r time_yr}

dat %>%
  ggplot(aes(x = days_fever)) +
  geom_histogram(bins = 50) +
  xlim(c(0,365)) +
  annotate("text", x = 300, y = 300, size = 2, label = "Axis cut at 365 days\nN = 3 cases with delay > 365.") +
  # facet_wrap(~diag_year) +
  labs(x = "Onset to diagnosis (days)", y = "Frequency") -> delay_hist
delay_hist

ggsave(here::here(figdir,"delay_hist.png"),
       delay_hist,
       height = 4, width = 5, units = "in")

```

### By month

```{r time_mth}

dat %>%
  st_drop_geometry() %>%
  group_by(diag_month) %>%
  summarise(N = n(),
            mean = mean(days_fever, na.rm = T),
            median = median(days_fever, na.rm = T),
            q1 = quantile(days_fever, p = 0.05, na.rm = T),
            q3 = quantile(days_fever, p = 0.95, na.rm = T),
            `> 90 days` = sum(days_fever > 90, na.rm = T)/N,
            `31-90 days` = sum(between(days_fever,31,90), na.rm = T)/N,
            `<= 30 days` = sum(days_fever <= 30, na.rm = T)/N) %>%
  ungroup() -> by_mth

by_mth %>%
  ggplot(aes(x = diag_month, group = 1, y = median, ymin = q1, ymax = q3)) +
  geom_errorbar(width = 0.5) +
  geom_point() +
  geom_line(aes(y = mean), col = "steelblue", lty = "dashed", lwd = 1.2) +
  scale_y_continuous(trans = "log2") +
  labs(x = "Month of diagnosis", y = "Onset to diagnosis (days)") -> delay_bymth
delay_bymth

ggsave(here::here(figdir,"delay_bymth.png"),
       delay_bymth,
       height = 4, width = 6, units = "in")


pal <- viridis::viridis(3, end = 0.8, direction = -1)
by_mth %>%
  pivot_longer(c(`> 90 days`,`31-90 days`,`<= 30 days`), names_to = "Delay") %>%
  mutate(Delay = factor(Delay, levels = c("<= 30 days", "31-90 days", "> 90 days"))) %>%
  ggplot(aes(x = diag_month, y = value, fill = Delay)) +
  geom_col() +
  scale_fill_manual(values = pal) +
  labs(x = "Month of diagnosis", y = "Proportion") -> prop_excessive
prop_excessive

ggsave(here::here(figdir,"prop_excessive_bymth.png"),
       prop_excessive,
       height = 4, width = 6, units = "in")

```


## Observed delays by location

### Individuals

+ Continuous, 5 categories, 3 categories and binary

```{r indiv}

## Continuous

plotdat <- arrange(st_jitter(dat), days_fever)

ggmap(bh_lines, 
      base_layer = ggplot(plotdat, aes(col = days_fever))) +
  geom_sf(alpha = 0.5, cex = 0.8) +
  scale_colour_viridis_c(trans = "log10", direction = -1, option = "plasma") +
  labs(x = "", y = "", col = "Delay", subtitle = "Diagnoses between Jan 2018 - July 2019") -> map_village
map_village

ggsave(here::here(figdir,"delay_individual.png"),
       map_village,
       height = 7, width = 10, units = "in")


## 5 categories
ggmap(bh_lines, 
      base_layer = ggplot(plotdat, 
                          aes(col = delay_cat5))) +
  geom_sf(alpha = 0.5, cex = 0.8) +
  scale_colour_viridis_d(option = "viridis", na.value = "grey", direction = -1, end = 0.9) +
  labs(x = "", y = "", col = "Delay") -> map_cat5
map_cat5

ggsave(here::here(figdir, "delay_cat5.png"), 
       map_cat5, 
       height = 7, width = 10, units = "in")

## 3 categories
ggmap(bh_lines, 
      base_layer = ggplot(plotdat, 
                          aes(col = delay_cat3))) +
  geom_sf(alpha = 0.8, cex = 0.8) +
  scale_colour_viridis_d(option = "viridis", na.value = "grey", direction = -1, end = 0.85) +
  labs(x = "", y = "", col = "Delay") -> map_cat3
map_cat3

ggsave(here::here(figdir, "delay_cat3.png"), 
       map_cat3, 
       height = 6, width = 8, units = "in")


## Binary > 90 days
ggmap(bh_lines, 
      base_layer = ggplot(plotdat, aes(col = gt90))) +
  geom_sf(alpha = 0.5, cex = 0.8) +
  scale_colour_manual(values = c("grey","indianred")) +
  labs(x = "", y = "", col = "Delay > 90 days", subtitle = "Diagnoses between Jan 2018 - July 2019") -> map_excess
map_excess

ggsave(here::here(figdir, "delay_excess.png"), 
       map_excess, 
       height = 7, width = 10, units = "in")

```


### By village

```{r village}

dat %>%
  group_by(vil_code) %>%
  summarise(N = n(),
            pop = unique(population),
            inc = replace_na(N*1e3/unique(pop),0),
            medianOD = median(days_fever, na.rm = T),
            propgt30 = mean((days_fever > 30), na.rm = T)*100,
            propgt90 = mean((days_fever > 90), na.rm = T)*100) %>%
  arrange(propgt90) -> by_village

## Median
ggmap(bh_lines, 
      base_layer = ggplot(by_village, 
                          aes(col = medianOD))) +
  geom_sf(alpha = 0.7, pch = 19) +
  scale_colour_viridis_c(option = "viridis", na.value = "grey", direction = -1, trans = "log2", end = 0.9) +
  scale_alpha_continuous(trans = "log10") +
  labs(x = "", y = "", col = "Median delay") -> map_medOD
map_medOD

ggsave(here::here(figdir, "village_median.png"), 
       map_medOD, 
       height = 7, width = 10, units = "in")


## % greater than 30 days
ggmap(bh_lines, 
      base_layer = ggplot(by_village, 
                          aes(col = propgt30))) +
  geom_sf(alpha = 0.7, pch = 19) +
  scale_colour_viridis_c(option = "magma", na.value = "grey", direction = -1, end = 0.9) +
  scale_alpha_continuous(trans = "log10") +
  labs(x = "", y = "", col = "% > 30 days") -> map_propgt30
map_propgt30

ggsave(here::here(figdir, "village_propgt30.png"), 
       map_propgt30, 
       height = 7, width = 10, units = "in")


## % greater than 90 days
ggmap(bh_lines, 
      base_layer = ggplot(by_village, 
                          aes(col = propgt90))) +
  geom_sf(alpha = 0.7, pch = 19) +
  scale_colour_viridis_c(option = "magma", na.value = "grey", direction = -1, end = 0.9) +
  scale_alpha_continuous(trans = "log10") +
  labs(x = "", y = "", col = "% > 90 days") -> map_propgt90
map_propgt90

ggsave(here::here(figdir, "village_propgt90.png"), 
       map_propgt90, 
       height = 7, width = 10, units = "in")

```

### By block

```{r block}

dat %>%
  st_drop_geometry() %>%
  group_by(district, block) %>%
  summarise(N = n(),
            medianOD = median(days_fever, na.rm = T),
            propgt90 = mean(gt90, na.rm = T)*100,
            propgt30 = mean(gt30, na.rm = T)*100) %>%
  mutate(ODcat3 = cut(medianOD, c(0,15,90,730), include.lowest = TRUE, ordered_result = TRUE)) %>%
  ungroup() -> by_block

by_block <- blockmap %>%
  left_join(by_block, by = c("kamis_master_dist" = "district", "kamis_master_block" = "block")) %>%
  rowwise() %>%
  mutate(pop = median(c_across(`2018`:`2019`)),
         inc = N*1e4/pop) %>%
  ungroup() 

# pal3 <- viridis::viridis(3)
ggplot() +
  geom_sf(data = blockmap) +
  geom_sf(data = by_block, aes(geometry = geometry, fill = medianOD)) +
  scale_fill_viridis_c(option = "viridis", na.value = "white", direction = -1, trans = "log2", end = 0.9) +
  labs(fill = "Median delay") + 
  theme(axis.text = element_blank()) -> blk_medOD
blk_medOD

ggsave(here::here(figdir, "block_medianOD.png"), blk_medOD, height = 7, width = 10, units = "in")

ggplot() +
  geom_sf(data = blockmap) +
  geom_sf(data = by_block, aes(geometry = geometry, fill = propgt30)) +
  scale_fill_viridis_c(option = "magma", na.value = "white", direction = -1, end = 0.8) +
  labs(fill = "% > 30 days") + 
  theme(axis.text = element_blank()) -> blk_pgt30
blk_pgt30

ggsave(here::here(figdir, "block_propgt30.png"), blk_pgt30, height = 7, width = 10, units = "in")


ggplot() +
  geom_sf(data = blockmap) +
  geom_sf(data = by_block, aes(geometry = geometry, fill = propgt90)) +
  scale_fill_viridis_c(option = "magma", na.value = "white", direction = -1, end = 0.9) +
  labs(fill = "% > 90 days") +
  theme(axis.text = element_blank()) -> blk_pgt90
blk_pgt90

ggsave(here::here(figdir, "block_propgt90.png"), blk_pgt90, height = 7, width = 10, units = "in")

# Join two block maps
combined <- blk_pgt30 + blk_pgt90 +
  plot_annotation(title = "Proportion of cases diagnosed with excess delays",
                  caption = paste0("Diagnoses between ",
                                   range(dat$diag_month)[1],
                                   " and ",
                                   range(dat$diag_month)[2]))
combined

ggsave(here::here(figdir, "excess_delay_byblock.png"), combined, height = 7, width = 14, units = "in")

```

```{r bivmap}

by_block %>%
  filter(!is.na(propgt30)) %>%
  mutate(inc = replace_na(inc, 0)) -> plotdat

bv <- create_bivmap(blockmap, plotdat,
                   xvar = "propgt30", yvar = "inc",
                   xlab = "% > 30 days", ylab = "Cases/10,000",
                   pal = "DkBlue",
                   style = "quantile")
bv

ggsave(here::here(figdir, "block_propgt30_byinc_bv.png"), bv, height = 7, width = 10, units = "in")

```
```{r by_blk_mth}

dat %>%
  st_drop_geometry() %>%
  mutate(diag_q = lubridate::quarter(diag_date, with_year = TRUE)) %>%
  group_by(district, block, diag_q) %>%
  summarise(N = n(),
            medianOD = median(days_fever, na.rm = T),
            propgt90 = mean(gt90, na.rm = T)*100,
            propgt30 = mean(gt30, na.rm = T)*100) %>%
  mutate(ODcat3 = cut(medianOD, c(0,15,90,730), include.lowest = TRUE, ordered_result = TRUE)) %>%
  ungroup() %>%
  complete(diag_q, nesting(district, block), fill = list(N = 0)) -> by_block

by_block <- blockmap %>%
  left_join(by_block, by = c("kamis_master_dist" = "district", "kamis_master_block" = "block")) %>%
  rowwise() %>%
  mutate(pop = median(c_across(`2018`:`2019`)),
         inc = N*1e4/pop) %>%
  ungroup() 

by_block %>%
  filter(!is.na(propgt30)) %>%
  mutate(inc = replace_na(inc, 0)) %>%
  arrange(diag_q) -> plotdat

for (q in unique(plotdat$diag_q)) {
bv <- create_bivmap(blockmap, filter(plotdat, diag_q == q),
                   xvar = "propgt30", yvar = "inc",
                   xlab = "% > 30 days", ylab = "Cases/10,000",
                   pal = "DkBlue",
                   style = "equal",
                   title = q) 
bv

ggsave(here::here(figdir,"by month",paste0("block_propgt30_byinc_",q,".png")), bv, height = 7, width = 10, units = "in")

}
```

## Non-parametric analysis of delay

```{r vgm}

# dat <- filter(dat, !is.na(longitude) & !is.na(days_fever_cdf))

# convert simple data frame into a spatial data frame object
dat.spdf <- as_Spatial(dat)

vg <- variogram(days_fever~1, data = dat)
plot(vg)

vgmod <- vgm(psill =  800, model = "Mat", nugget = 1000, range = 100)
plot(vg, model = vgmod)

vgfit <- fit.variogram(vg, model = vgmod)    
plot(vg, model = vgfit)

vgfit
# model    psill    range kappa
# Nug 936.1536 0.000000   0.0
# Mat 959.9353 0.629266   0.5

png(here::here(figdir, "delay_semivariogram.png"), height = 500, width = 600)
plot(vg, model = vgfit)
dev.off()


```

## Covariate effects

```{r covs_indiv}

plotdat <- st_drop_geometry(dat)

# Found to be significant in Dubey et al.
dat %>%
  ggplot(aes(age, days_fever)) +
  geom_jitter(alpha = 0.1) 

dat %>%
  ggplot(aes(sex, days_fever)) +
  geom_boxplot()

dat %>%
  ggplot(aes(hiv, days_fever)) +
  geom_boxplot()

dat %>%
  ggplot(aes(caste4, days_fever)) +
  geom_boxplot()

dat %>%
  ggplot(aes(mahadalit4, days_fever)) +
  geom_boxplot()

dat %>%
  ggplot(aes(prv_tx_ka, days_fever)) +
  geom_boxplot()

```


```{r covs_physical}


dat %>%
  st_drop_geometry() %>%
  ggplot(aes(traveltime, days_fever)) +
  geom_jitter(alpha = 0.1) 
  # scale_y_continuous(trans = "log10")


dat %>%
  st_drop_geometry() %>%
  ggplot(aes(gt30, traveltime + 1)) +
  geom_boxplot() +
  scale_y_continuous(trans = "log2")

dat %>%
  st_drop_geometry() %>%
  ggplot(aes(gt90, traveltime + 1)) +
  geom_boxplot() +
  scale_y_continuous(trans = "log2")



```


```{r covs_riskperception}


dat %>%
  st_drop_geometry() %>%
  ggplot(aes(traveltime, days_fever)) +
  geom_jitter(alpha = 0.1) 
  # scale_y_continuous(trans = "log10")


dat %>%
  st_drop_geometry() %>%
  ggplot(aes(gt30, traveltime + 1)) +
  geom_boxplot() +
  scale_y_continuous(trans = "log2")

dat %>%
  st_drop_geometry() %>%
  ggplot(aes(gt90, traveltime + 1)) +
  geom_boxplot() +
  scale_y_continuous(trans = "log2")



```